name: Qgoda GitHub Pages Action
description: Builds a static site with Qgoda and deploys it to the github-pages branch
author: Guido Flohr
branding:
  icon: book-open
  color: blue

inputs:
  qgoda-version:
    description: Version of Qgoda to use, defaults to 'latest'
    default: latest
  
  qgoda-image:
    description: Which docker image to use, defaults to 'gflohr/qgoda'
    default: gflohr/qgoda
  
  qgoda-srcdir:
    description: Relative path to your source files, defaults to '.'
    default: .

  qgoda-command:
    description: The qgoda command to run, defaults to 'build'
    default: build

  image-data:
    description: Working directory inside container image, defaults to '/data'
    default: /data

  docker-registry:
    description: The container registry to use, defaults to 'docker.io'
    default: 'docker.io'

runs:
  using: composite
  steps:
    - name: Pull image
      run: docker pull docker.io/gflohr/qgoda:v0.10.1
      shell: sh

    - name: Build site
      run: docker run --rm -v ${{ github.workspace }}/.:/data docker.io/gflohr/qgoda:v0.10.1 --verbose build
      shell: sh
