name: 'Qgoda GitHub Pages Action'
description: 'Builds a static site with Qgoda and deploys it to the github-pages branch'
author: 'Guido Flohr'
branding:
  icon: 'book-open'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub Token for pushing to the github-pages branch'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/entrypoint.sh'

