name: Qgoda GitHub Pages Action
description: Builds a static site with Qgoda and deploys it to the github-pages branch
author: Guido Flohr
branding:
  icon: book-open
  color: blue

inputs:
  docker-registry:
    description: The container registry to use, defaults to 'docker.io'
    default: 'docker.io'

  qgoda-image:
    description: Which docker image to use, defaults to 'gflohr/qgoda'
    default: gflohr/qgoda
  
  qgoda-version:
    description: Version of Qgoda to use, defaults to 'latest-node'
    default: latest-node
  
  qgoda-srcdir:
    description: Relative path to your source files, defaults to '.'
    default: .

  qgoda-command:
    description: The qgoda command to run, defaults to 'build'
    default: build

  image-data:
    description: Working directory inside container image, defaults to '/data'
    default: /data

runs:
  using: composite
  steps:
    - name: Pull Qgoda image
      run: docker pull ${{ inputs.docker-registry }}/${{ inputs.qgoda-image }}:${{ inputs.qgoda-version }}
      shell: sh

    - name: Build site with Qgoda
      run: docker run --rm -v ${{ github.workspace }}/${{ inputs.qgoda-srcdir }}:${{ inputs.image-data }} ${{ inputs.docker-registry }}/${{ inputs.qgoda-image }}:${{ inputs.qgoda-version }} --verbose ${{ inputs.qgoda-command }}
      shell: sh
