name: Qgoda GitHub Pages Action
description: Builds a static site with Qgoda and deploys it to the github-pages branch
author: Guido Flohr
branding:
  icon: globe
  color: blue

inputs:
  docker-registry:
    description: The container registry to use, defaults to 'docker.io'
    default: 'docker.io'

  qgoda-image:
    description: Which docker image to use, defaults to 'gflohr/qgoda'
    default: gflohr/qgoda
  
  qgoda-version:
    description: Version of Qgoda to use, defaults to 'latest-node'
    default: latest-node
  
  qgoda-srcdir:
    description: Relative path to your source files, defaults to '.'
    default: .

  qgoda-command:
    description: The qgoda command to run, defaults to 'build'
    default: build

  image-data:
    description: Working directory inside container image, defaults to '/data'
    default: /data
  
  alpine-dependencies:
    description: Additional dependencies to be added with 'apk add', defaults to empty
    default: ''

runs:
  using: composite
  steps:
    - name: Pull Qgoda image
      run: docker pull ${{ inputs.docker-registry }}/${{ inputs.qgoda-image }}:${{ inputs.qgoda-version }}
      shell: sh

    # The user qgoda must be able to write into the /data directory.
    - name: Chown ownership
      run: |
        docker run --user=root -entrypoint=chown --rm \
          -v ${{ github.workspace }}/${{ inputs.qgoda-srcdir }}:${{ inputs.image-data }} \
          ${{ inputs.docker-registry }}/${{ inputs.qgoda-image }}:${{ inputs.qgoda-version }} \
          -R qgoda ${{ inputs.image-data }}
      shell: sh

    # Install optional dependencies.
    - name: Install alpine dependencies
      if: ${{ inputs.alpine-dependencies != '' }}
      run: |
        docker run --user=root --entrypoint=apk --rm \
          -v qgoda-volume:/usr \
          ${{ inputs.docker-registry }}/${{ inputs.qgoda-image }}:${{ inputs.qgoda-version }} \
          add ${{ inputs.alpine-dependencies }}
      shell: sh

    # If plug-ins are installed as a dependency from package.json, they must
    # be installed before qgoda can start.
    - name: Install Qgoda dependencies
      if: ${{ hashFiles(format('{0}/package.json', inputs.qgoda-srcdir)) != '' }}
      run: |
        docker run --entrypoint=npm --rm \
          -v qgoda-volum:/usr \
          -v ${{ github.workspace }}/${{ inputs.qgoda-srcdir }}:${{ inputs.image-data }} \
          ${{ inputs.docker-registry }}/${{ inputs.qgoda-image }}:${{ inputs.qgoda-version }} \
          install
      shell: sh

    - name: Build site with Qgoda
      run: |
        docker run --rm \
          -v qgoda-volume:/usr \
          -v ${{ github.workspace }}/${{ inputs.qgoda-srcdir }}:${{ inputs.image-data }} \
          ${{ inputs.docker-registry }}/${{ inputs.qgoda-image }}:${{ inputs.qgoda-version }} \
          ${{ inputs.qgoda-command }}
      shell: sh
